spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3307/my_app
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
